### ISSUE TITLE
Installation failing in Brackets 1.9

### ISSUE THREAD

**Issue by ghost** [nmaxcom/brackets-autosaver#6] opened 2017-05-22 15:37 UTC
Installation is failing on new brackets update.

**Comment by nmaxcom** [comment] 2017-06-25 10:32
What does it happen? Is there any error message?

Nevertheless I think it's a duplicate of #7 of the new Brackets API. I'm looking into it. Thanks.

**Closed as completed** 2017-06-25 10:32 UTC
Labels: duplicate
